// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DemoFilter.proto

package org.sober.filter.demo;

public final class DemoFilterProtoV1 {
  private DemoFilterProtoV1() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DemoFilterProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 limit = 1;
    /**
     * <code>required int32 limit = 1;</code>
     */
    boolean hasLimit();
    /**
     * <code>required int32 limit = 1;</code>
     */
    int getLimit();

    // required int32 offset = 2;
    /**
     * <code>required int32 offset = 2;</code>
     */
    boolean hasOffset();
    /**
     * <code>required int32 offset = 2;</code>
     */
    int getOffset();

    // required int32 count = 3;
    /**
     * <code>required int32 count = 3;</code>
     */
    boolean hasCount();
    /**
     * <code>required int32 count = 3;</code>
     */
    int getCount();

    // required string filterField = 4;
    /**
     * <code>required string filterField = 4;</code>
     */
    boolean hasFilterField();
    /**
     * <code>required string filterField = 4;</code>
     */
    java.lang.String getFilterField();
    /**
     * <code>required string filterField = 4;</code>
     */
    com.google.protobuf.ByteString
        getFilterFieldBytes();

    // required string filterValue = 5;
    /**
     * <code>required string filterValue = 5;</code>
     */
    boolean hasFilterValue();
    /**
     * <code>required string filterValue = 5;</code>
     */
    java.lang.String getFilterValue();
    /**
     * <code>required string filterValue = 5;</code>
     */
    com.google.protobuf.ByteString
        getFilterValueBytes();
  }
  /**
   * Protobuf type {@code DemoFilterProto}
   */
  public static final class DemoFilterProto extends
      com.google.protobuf.GeneratedMessage
      implements DemoFilterProtoOrBuilder {
    // Use DemoFilterProto.newBuilder() to construct.
    private DemoFilterProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DemoFilterProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DemoFilterProto defaultInstance;
    public static DemoFilterProto getDefaultInstance() {
      return defaultInstance;
    }

    public DemoFilterProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DemoFilterProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              limit_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              offset_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              count_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              filterField_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              filterValue_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DemoFilterProtoV1.internal_static_DemoFilterProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DemoFilterProtoV1.internal_static_DemoFilterProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DemoFilterProtoV1.DemoFilterProto.class, DemoFilterProtoV1.DemoFilterProto.Builder.class);
    }

    public static com.google.protobuf.Parser<DemoFilterProto> PARSER =
        new com.google.protobuf.AbstractParser<DemoFilterProto>() {
      public DemoFilterProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DemoFilterProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DemoFilterProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 limit = 1;
    public static final int LIMIT_FIELD_NUMBER = 1;
    private int limit_;
    /**
     * <code>required int32 limit = 1;</code>
     */
    public boolean hasLimit() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 limit = 1;</code>
     */
    public int getLimit() {
      return limit_;
    }

    // required int32 offset = 2;
    public static final int OFFSET_FIELD_NUMBER = 2;
    private int offset_;
    /**
     * <code>required int32 offset = 2;</code>
     */
    public boolean hasOffset() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 offset = 2;</code>
     */
    public int getOffset() {
      return offset_;
    }

    // required int32 count = 3;
    public static final int COUNT_FIELD_NUMBER = 3;
    private int count_;
    /**
     * <code>required int32 count = 3;</code>
     */
    public boolean hasCount() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 count = 3;</code>
     */
    public int getCount() {
      return count_;
    }

    // required string filterField = 4;
    public static final int FILTERFIELD_FIELD_NUMBER = 4;
    private java.lang.Object filterField_;
    /**
     * <code>required string filterField = 4;</code>
     */
    public boolean hasFilterField() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string filterField = 4;</code>
     */
    public java.lang.String getFilterField() {
      java.lang.Object ref = filterField_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          filterField_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string filterField = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFilterFieldBytes() {
      java.lang.Object ref = filterField_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filterField_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string filterValue = 5;
    public static final int FILTERVALUE_FIELD_NUMBER = 5;
    private java.lang.Object filterValue_;
    /**
     * <code>required string filterValue = 5;</code>
     */
    public boolean hasFilterValue() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string filterValue = 5;</code>
     */
    public java.lang.String getFilterValue() {
      java.lang.Object ref = filterValue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          filterValue_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string filterValue = 5;</code>
     */
    public com.google.protobuf.ByteString
        getFilterValueBytes() {
      java.lang.Object ref = filterValue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filterValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      limit_ = 0;
      offset_ = 0;
      count_ = 0;
      filterField_ = "";
      filterValue_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasLimit()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOffset()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFilterField()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFilterValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, limit_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, offset_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, count_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getFilterFieldBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getFilterValueBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, limit_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, offset_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, count_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getFilterFieldBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getFilterValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DemoFilterProtoV1.DemoFilterProto)) {
        return super.equals(obj);
      }
      DemoFilterProtoV1.DemoFilterProto other = (DemoFilterProtoV1.DemoFilterProto) obj;

      boolean result = true;
      result = result && (hasLimit() == other.hasLimit());
      if (hasLimit()) {
        result = result && (getLimit()
            == other.getLimit());
      }
      result = result && (hasOffset() == other.hasOffset());
      if (hasOffset()) {
        result = result && (getOffset()
            == other.getOffset());
      }
      result = result && (hasCount() == other.hasCount());
      if (hasCount()) {
        result = result && (getCount()
            == other.getCount());
      }
      result = result && (hasFilterField() == other.hasFilterField());
      if (hasFilterField()) {
        result = result && getFilterField()
            .equals(other.getFilterField());
      }
      result = result && (hasFilterValue() == other.hasFilterValue());
      if (hasFilterValue()) {
        result = result && getFilterValue()
            .equals(other.getFilterValue());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasLimit()) {
        hash = (37 * hash) + LIMIT_FIELD_NUMBER;
        hash = (53 * hash) + getLimit();
      }
      if (hasOffset()) {
        hash = (37 * hash) + OFFSET_FIELD_NUMBER;
        hash = (53 * hash) + getOffset();
      }
      if (hasCount()) {
        hash = (37 * hash) + COUNT_FIELD_NUMBER;
        hash = (53 * hash) + getCount();
      }
      if (hasFilterField()) {
        hash = (37 * hash) + FILTERFIELD_FIELD_NUMBER;
        hash = (53 * hash) + getFilterField().hashCode();
      }
      if (hasFilterValue()) {
        hash = (37 * hash) + FILTERVALUE_FIELD_NUMBER;
        hash = (53 * hash) + getFilterValue().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DemoFilterProtoV1.DemoFilterProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DemoFilterProtoV1.DemoFilterProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DemoFilterProtoV1.DemoFilterProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DemoFilterProtoV1.DemoFilterProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DemoFilterProtoV1.DemoFilterProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DemoFilterProtoV1.DemoFilterProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static DemoFilterProtoV1.DemoFilterProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static DemoFilterProtoV1.DemoFilterProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static DemoFilterProtoV1.DemoFilterProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DemoFilterProtoV1.DemoFilterProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(DemoFilterProtoV1.DemoFilterProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DemoFilterProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements DemoFilterProtoV1.DemoFilterProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DemoFilterProtoV1.internal_static_DemoFilterProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DemoFilterProtoV1.internal_static_DemoFilterProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DemoFilterProtoV1.DemoFilterProto.class, DemoFilterProtoV1.DemoFilterProto.Builder.class);
      }

      // Construct using org.sober.demo.DemoFilterProtoV1.DemoFilterProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        limit_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        offset_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        count_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        filterField_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        filterValue_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DemoFilterProtoV1.internal_static_DemoFilterProto_descriptor;
      }

      public DemoFilterProtoV1.DemoFilterProto getDefaultInstanceForType() {
        return DemoFilterProtoV1.DemoFilterProto.getDefaultInstance();
      }

      public DemoFilterProtoV1.DemoFilterProto build() {
        DemoFilterProtoV1.DemoFilterProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public DemoFilterProtoV1.DemoFilterProto buildPartial() {
        DemoFilterProtoV1.DemoFilterProto result = new DemoFilterProtoV1.DemoFilterProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.limit_ = limit_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.offset_ = offset_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.count_ = count_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.filterField_ = filterField_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.filterValue_ = filterValue_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DemoFilterProtoV1.DemoFilterProto) {
          return mergeFrom((DemoFilterProtoV1.DemoFilterProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DemoFilterProtoV1.DemoFilterProto other) {
        if (other == DemoFilterProtoV1.DemoFilterProto.getDefaultInstance()) return this;
        if (other.hasLimit()) {
          setLimit(other.getLimit());
        }
        if (other.hasOffset()) {
          setOffset(other.getOffset());
        }
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        if (other.hasFilterField()) {
          bitField0_ |= 0x00000008;
          filterField_ = other.filterField_;
          onChanged();
        }
        if (other.hasFilterValue()) {
          bitField0_ |= 0x00000010;
          filterValue_ = other.filterValue_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLimit()) {
          
          return false;
        }
        if (!hasOffset()) {
          
          return false;
        }
        if (!hasCount()) {
          
          return false;
        }
        if (!hasFilterField()) {
          
          return false;
        }
        if (!hasFilterValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DemoFilterProtoV1.DemoFilterProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DemoFilterProtoV1.DemoFilterProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 limit = 1;
      private int limit_ ;
      /**
       * <code>required int32 limit = 1;</code>
       */
      public boolean hasLimit() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 limit = 1;</code>
       */
      public int getLimit() {
        return limit_;
      }
      /**
       * <code>required int32 limit = 1;</code>
       */
      public Builder setLimit(int value) {
        bitField0_ |= 0x00000001;
        limit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 limit = 1;</code>
       */
      public Builder clearLimit() {
        bitField0_ = (bitField0_ & ~0x00000001);
        limit_ = 0;
        onChanged();
        return this;
      }

      // required int32 offset = 2;
      private int offset_ ;
      /**
       * <code>required int32 offset = 2;</code>
       */
      public boolean hasOffset() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 offset = 2;</code>
       */
      public int getOffset() {
        return offset_;
      }
      /**
       * <code>required int32 offset = 2;</code>
       */
      public Builder setOffset(int value) {
        bitField0_ |= 0x00000002;
        offset_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 offset = 2;</code>
       */
      public Builder clearOffset() {
        bitField0_ = (bitField0_ & ~0x00000002);
        offset_ = 0;
        onChanged();
        return this;
      }

      // required int32 count = 3;
      private int count_ ;
      /**
       * <code>required int32 count = 3;</code>
       */
      public boolean hasCount() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 count = 3;</code>
       */
      public int getCount() {
        return count_;
      }
      /**
       * <code>required int32 count = 3;</code>
       */
      public Builder setCount(int value) {
        bitField0_ |= 0x00000004;
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 count = 3;</code>
       */
      public Builder clearCount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        count_ = 0;
        onChanged();
        return this;
      }

      // required string filterField = 4;
      private java.lang.Object filterField_ = "";
      /**
       * <code>required string filterField = 4;</code>
       */
      public boolean hasFilterField() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string filterField = 4;</code>
       */
      public java.lang.String getFilterField() {
        java.lang.Object ref = filterField_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          filterField_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string filterField = 4;</code>
       */
      public com.google.protobuf.ByteString
          getFilterFieldBytes() {
        java.lang.Object ref = filterField_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          filterField_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string filterField = 4;</code>
       */
      public Builder setFilterField(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        filterField_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string filterField = 4;</code>
       */
      public Builder clearFilterField() {
        bitField0_ = (bitField0_ & ~0x00000008);
        filterField_ = getDefaultInstance().getFilterField();
        onChanged();
        return this;
      }
      /**
       * <code>required string filterField = 4;</code>
       */
      public Builder setFilterFieldBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        filterField_ = value;
        onChanged();
        return this;
      }

      // required string filterValue = 5;
      private java.lang.Object filterValue_ = "";
      /**
       * <code>required string filterValue = 5;</code>
       */
      public boolean hasFilterValue() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string filterValue = 5;</code>
       */
      public java.lang.String getFilterValue() {
        java.lang.Object ref = filterValue_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          filterValue_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string filterValue = 5;</code>
       */
      public com.google.protobuf.ByteString
          getFilterValueBytes() {
        java.lang.Object ref = filterValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          filterValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string filterValue = 5;</code>
       */
      public Builder setFilterValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        filterValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string filterValue = 5;</code>
       */
      public Builder clearFilterValue() {
        bitField0_ = (bitField0_ & ~0x00000010);
        filterValue_ = getDefaultInstance().getFilterValue();
        onChanged();
        return this;
      }
      /**
       * <code>required string filterValue = 5;</code>
       */
      public Builder setFilterValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        filterValue_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:DemoFilterProto)
    }

    static {
      defaultInstance = new DemoFilterProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:DemoFilterProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_DemoFilterProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DemoFilterProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020DemoFilter.proto\"i\n\017DemoFilterProto\022\r\n" +
      "\005limit\030\001 \002(\005\022\016\n\006offset\030\002 \002(\005\022\r\n\005count\030\003 " +
      "\002(\005\022\023\n\013filterField\030\004 \002(\t\022\023\n\013filterValue\030" +
      "\005 \002(\tB+\n\016org.sober.demoB\021DemoFilterProto" +
      "V1H\001\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_DemoFilterProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_DemoFilterProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_DemoFilterProto_descriptor,
              new java.lang.String[] { "Limit", "Offset", "Count", "FilterField", "FilterValue", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
